import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* we have created this providers component otherwise would need to use SessionProvider component from
        next-auth library, which demands to use "use client" on top of this page, which attracts lots of issues so 
        we created this component which returns the SessionProvider and use safely the "use client" */}
        <Providers>
        {children}
        </Providers>
      </body>
    </html>
  );
}
