import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers, ThemeProvider } from "./providers";

// to be continued here
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-[#1b1934b2]`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" disableTransitionOnChange enableSystem>
          {/* we have created this providers component otherwise would need to use SessionProvider component from
          next-auth library, which demands to use "use client" on top of this page, which attracts lots of issues so 
          we created this component which returns the SessionProvider and use safely the "use client" */}
          <Providers>
          {children}
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
